# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReleaseMnagement.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from class_release import AutoRelease

import time
import sys


class Ui_MainWindow(object):
    def __init__(self):
        self.statusbar = None
        self.Run_btn = None
        self.centralwidget = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(420, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Run_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Run_btn.setGeometry(QtCore.QRect(100, 40, 211, 51))
        self.Run_btn.setObjectName("Run_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.Run_btn.clicked.connect(self.Process)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AutoRelease"))
        self.Run_btn.setText(_translate("MainWindow", "Start"))

    @staticmethod
    def Process():
        # 外面需要嵌套一个for循环
        current_release_number = 'RLSE0011779'
        release = AutoRelease(current_release_number)  # 生成与本release有关的类

        query = "release=bcfe0d66dbe33910bfa850d3f3961908^state=13"

        start_time = time.time()
        release.main_procedure(query)
        end_time = time.time()
        print("Run time:", end_time - start_time, "s")


if __name__ == "__main__":

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)

    MainWindow.show()
    sys.exit(app.exec_())